// test/setup-menu.test.ts
//
// Smoke-tests for the setup menu pane bash script generated by
// buildSetupMenuScript(). The script handles polling for the config agent's
// CAM_SETUP_STATUS=DONE marker and spawning the orchestrator pane on detect.
//
// We can't run the script (it would require a real tmux session). What we
// CAN do cheaply and deterministically:
//
//   1. Run `bash -n` against the generated text to verify shell syntax.
//   2. Grep for the load-bearing structural markers — handoff() function,
//      polling regex, both menu states — so accidental refactors that drop
//      a critical line fail fast.

import { describe, expect, it } from 'bun:test';
import { mkdtempSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';

import { buildSetupMenuScript } from '../src/commands/setup.ts';

describe('buildSetupMenuScript', () => {
	it('generates valid bash (passes `bash -n` syntax check)', () => {
		const script = buildSetupMenuScript();
		const dir = mkdtempSync(join(tmpdir(), 'cam-menu-'));
		const file = join(dir, 'menu.sh');
		writeFileSync(file, script, 'utf8');
		const r = spawnSync('bash', ['-n', file], { encoding: 'utf8' });
		expect(r.status).toBe(0);
		// stderr should be empty on success
		expect(r.stderr ?? '').toBe('');
	});

	it('declares the handoff function that spawns the orchestrator pane', () => {
		const script = buildSetupMenuScript();
		expect(script).toContain('handoff()');
		expect(script).toContain('tmux split-window');
		expect(script).toContain('--permission-mode bypassPermissions');
	});

	it('polls for CAM_SETUP_STATUS=DONE in the config pane', () => {
		const script = buildSetupMenuScript();
		expect(script).toContain('CAM_SETUP_STATUS=DONE');
		expect(script).toContain('tmux capture-pane');
		// The 2s timeout for read makes polling work without busy-looping.
		expect(script).toContain('read -rsn1 -t 2');
	});

	it('declares both initial and post-setup menu states', () => {
		const script = buildSetupMenuScript();
		expect(script).toContain('show_initial');
		expect(script).toContain('show_post');
		expect(script).toContain('state=initial');
		expect(script).toContain('state=post');
	});

	it('reads CAM_CONFIG_PANE and CAM_ORCH_PROMPT_FILE from env', () => {
		const script = buildSetupMenuScript();
		expect(script).toContain('CAM_CONFIG_PANE');
		expect(script).toContain('CAM_ORCH_PROMPT_FILE');
	});

	it('exits cleanly on q in either state', () => {
		const script = buildSetupMenuScript();
		// Both case statements must include q|Q -> exit 0.
		const matches = script.match(/q\|Q\) exit 0/g);
		expect(matches).not.toBeNull();
		expect(matches!.length).toBeGreaterThanOrEqual(2);
	});

	it('post-setup menu allows killing the config pane', () => {
		const script = buildSetupMenuScript();
		expect(script).toContain('tmux kill-pane');
	});
});
