// src/runtime/claude-credential.ts
//
// File-backed storage for the Claude provider's own dedicated subscription
// token (GSHIP-704), generated by `claude setup-token`. Lives under
// GATESHIP_HOME -- the global product home, never a project's own repository
// or `.gship` directory -- so one dedicated credential serves every project
// Gateship manages, and deleting a project's checkout never deletes it.
//
// Mirrors the Resend API key's own file-backed pattern in remote-notifier.ts:
// mode 0600, atomic write-then-rename, and an environment variable that wins
// over the file. Mode 0600 and the child environment allowlist prevent
// accidental disclosure; they do not isolate this file from a hostile
// provider process running with the same filesystem identity, and this is
// not encryption -- there is no external root of trust to claim one against.

import { randomUUID } from 'node:crypto';
import {
	chmodSync,
	closeSync,
	fsyncSync,
	mkdirSync,
	openSync,
	readFileSync,
	renameSync,
	statSync,
	unlinkSync,
	writeFileSync,
} from 'node:fs';
import { join } from 'node:path';

import { CLAUDE_CODE_OAUTH_TOKEN_ENV_VAR } from './provider-env.ts';

/** Bare filename under `GATESHIP_HOME`; no subdirectory needed for a single credential. */
export const CLAUDE_CREDENTIAL_FILE_NAME = 'claude-credential';

/**
 * Same refusal as the Resend key's own file read: absent, empty, or (on a
 * platform where `chmod` actually narrows access) looser than 600 all read
 * as no file. Windows' `chmodSync(0o600)` does not narrow the NTFS ACL the
 * way it narrows a POSIX mode, so `statSync` keeps reporting a wide mode
 * there regardless of what this module wrote; enforcing this check on
 * Windows would read a credential this same module just wrote as
 * permanently absent, which is exactly the silent external-login fallback
 * this issue forbids, on a platform GSHIP-704 explicitly requires covering.
 */
function readClaudeCredentialFile(gateshipHome: string): string | null {
	const path = join(gateshipHome, CLAUDE_CREDENTIAL_FILE_NAME);
	try {
		const enforceMode = process.platform !== 'win32';
		if (enforceMode && (statSync(path).mode & 0o077) !== 0) return null;
		const raw = readFileSync(path, 'utf8').trim();
		return raw.length === 0 ? null : raw;
	} catch {
		return null;
	}
}

/**
 * Writes a replacement token without ever exposing it through a return
 * value. A failed preparation leaves the previous valid token intact: the
 * temporary file is prepared and `chmod`ed before it replaces the live one.
 */
export function writeClaudeCredential(gateshipHome: string, token: string): void {
	const trimmed = token.trim();
	if (trimmed.length === 0) throw new Error('A non-empty token is required.');
	mkdirSync(gateshipHome, { recursive: true });
	const target = join(gateshipHome, CLAUDE_CREDENTIAL_FILE_NAME);
	const temporary = join(gateshipHome, `.${CLAUDE_CREDENTIAL_FILE_NAME}.${randomUUID()}.tmp`);
	let descriptor: number | null = null;
	try {
		descriptor = openSync(temporary, 'wx', 0o600);
		// Do not rely on the process umask to establish the credential boundary.
		chmodSync(temporary, 0o600);
		writeFileSync(descriptor, `${trimmed}\n`, 'utf8');
		fsyncSync(descriptor);
		closeSync(descriptor);
		descriptor = null;
		renameSync(temporary, target);
	} catch (error) {
		if (descriptor !== null) closeSync(descriptor);
		try { unlinkSync(temporary); } catch { /* Nothing was prepared. */ }
		throw error;
	}
}

/** Explicit disconnect. Returns whether a file was actually present to remove. */
export function removeClaudeCredential(gateshipHome: string): boolean {
	try {
		unlinkSync(join(gateshipHome, CLAUDE_CREDENTIAL_FILE_NAME));
		return true;
	} catch (error) {
		if (error instanceof Error && 'code' in error && error.code === 'ENOENT') return false;
		throw error;
	}
}

/**
 * Reads `CLAUDE_CODE_OAUTH_TOKEN` out of the service's own process
 * environment exactly once, at boot, and removes it immediately -- mirroring
 * the same rationale `test/helpers/reap-preload.ts`'s suite-wide guard
 * already documents. Without this, the value stays ambient in
 * `process.env` for the rest of the process's life and could reach an owned
 * child that explicitly forwards it. The two callers that legitimately need this
 * value, `resolveClaudeCredential` and `resolveClaudeCredentialStatus`, take
 * the returned snapshot explicitly instead of reading `process.env` again,
 * so deleting the live variable here does not change what either of them
 * resolves.
 */
export function captureBootClaudeToken(
	env: Record<string, string | undefined> = process.env,
): Record<string, string | undefined> {
	const value = env[CLAUDE_CODE_OAUTH_TOKEN_ENV_VAR];
	delete env[CLAUDE_CODE_OAUTH_TOKEN_ENV_VAR];
	return value === undefined ? {} : { [CLAUDE_CODE_OAUTH_TOKEN_ENV_VAR]: value };
}

/**
 * The one place precedence between the boot-time environment variable and
 * the file-backed credential is decided (GSHIP-704): the same rule the
 * Resend API key already follows -- the environment wins, so an automated
 * install can set `CLAUDE_CODE_OAUTH_TOKEN` without Settings ever
 * disagreeing with it. Absent both, `undefined` -- the existing external
 * login fallback -- never an empty string standing in for "not configured".
 * `env` is the snapshot `captureBootClaudeToken` already captured, not
 * `process.env` itself, which no longer carries this value after boot.
 */
export function resolveClaudeCredential(
	gateshipHome: string,
	env: Record<string, string | undefined> = process.env,
): string | undefined {
	const fromEnv = env[CLAUDE_CODE_OAUTH_TOKEN_ENV_VAR];
	const trimmedEnv = typeof fromEnv === 'string' ? fromEnv.trim() : '';
	if (trimmedEnv.length > 0) return trimmedEnv;
	return readClaudeCredentialFile(gateshipHome) ?? undefined;
}

/**
 * What Ajustes needs to decide whether a file write to Settings would take
 * effect: whether `CLAUDE_CODE_OAUTH_TOKEN` in the service environment would
 * override it regardless. Rotate/reconnect/disconnect availability itself
 * comes from `ProviderStatus.login === 'dedicated'`, not from this value --
 * that already reflects whether a credential (file or environment) is
 * configured, whether or not it currently resolves to a live subscription.
 * Takes the same `captureBootClaudeToken` snapshot `resolveClaudeCredential`
 * does -- reading `process.env` here directly would report `envManaged:
 * false` for an env-managed install, since boot already removed the live
 * variable.
 */
export interface ClaudeCredentialStatus {
	envManaged: boolean;
}

export function resolveClaudeCredentialStatus(
	env: Record<string, string | undefined> = process.env,
): ClaudeCredentialStatus {
	const fromEnv = env[CLAUDE_CODE_OAUTH_TOKEN_ENV_VAR];
	return {
		envManaged: typeof fromEnv === 'string' && fromEnv.trim().length > 0,
	};
}
