// test/spine/no-inline-specified-predicate.test.ts
//
// Spine guard (US-003, CAM-222 PRD): fails when any src/ file, outside the
// canonical plannable predicate module, inline-compares stage against the
// 'specified' literal via ===. This keeps the plannability predicate from
// silently re-duplicating outside src/issues/plannable.ts (see US-001).
//
// Why src/vendor/ is EXCLUDED from the scan root: src/vendor/_generated.ts
// is an auto-generated build-time embed (regenerated by `bun run
// embed-vendor`) that mirrors human-facing prose, e.g. it embeds the literal
// string `stage === 'specified'` verbatim from templates/commands/cam-plan.md
// at build time. It is already excluded from typecheck by design; it is not
// application logic, it is a frozen prose/document snapshot, so it is out of
// scan scope here too.
//
// Why this guard cannot self-trip: this file lives under test/, and the real
// scan root below is 'src/**/*.{ts,tsx}' only, so test/ is never scanned. The
// banned literal also never appears inline in this file's own source: the
// regex is built from string parts so no coincidental match exists.

import { describe, expect, test } from 'bun:test';
import { Glob } from 'bun';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

/** The single file allowed to inline-compare stage against 'specified'. */
export const ALLOWLISTED_FILE = 'src/issues/plannable.ts';

/** Matches `=== 'specified'` or `=== "specified"` (with optional whitespace). */
const INLINE_SPECIFIED_RE = new RegExp("===\\s*['\"]specified['\"]");

export interface Violation {
	path: string;
	line: number;
}

/**
 * Pure scanner: given an in-memory file list, returns one Violation per
 * matching line found outside the allowlist. Callers are responsible for
 * excluding src/vendor/ from the input file list (see header comment).
 */
export function findInlineSpecifiedViolations(
	files: { path: string; text: string }[],
	allowlist: string[] = [ALLOWLISTED_FILE],
): Violation[] {
	const violations: Violation[] = [];
	for (const { path, text } of files) {
		if (allowlist.includes(path)) continue;
		const lines = text.split('\n');
		for (let i = 0; i < lines.length; i++) {
			const lineText = lines[i] ?? '';
			if (INLINE_SPECIFIED_RE.test(lineText)) {
				violations.push({ path, line: i + 1 });
			}
		}
	}
	return violations;
}

// ---------------------------------------------------------------------------
// Unit tests: synthetic content, no real filesystem writes under src/
// ---------------------------------------------------------------------------

describe('findInlineSpecifiedViolations — synthetic', () => {
	test('flags a violating file outside the allowlist', () => {
		const violations = findInlineSpecifiedViolations([
			{ path: 'src/issues/rogue.ts', text: "if (entry.stage === 'specified') {}\n" },
		]);
		expect(violations).toEqual([{ path: 'src/issues/rogue.ts', line: 1 }]);
	});

	test('does not flag the allowlisted canonical predicate module', () => {
		const violations = findInlineSpecifiedViolations([
			{ path: ALLOWLISTED_FILE, text: "return entry.stage === 'specified' && entry.status === 'open';\n" },
		]);
		expect(violations).toEqual([]);
	});

	test('flags the double-quoted variant', () => {
		const violations = findInlineSpecifiedViolations([
			{ path: 'src/bar.ts', text: 'if (stage === "specified") {}\n' },
		]);
		expect(violations).toHaveLength(1);
		expect(violations[0]).toEqual({ path: 'src/bar.ts', line: 1 });
	});

	test('does not flag unrelated uses of the word specified', () => {
		const violations = findInlineSpecifiedViolations([
			{ path: 'src/foo.ts', text: "const x = 'specified';\nconst y = stage;\n" },
		]);
		expect(violations).toEqual([]);
	});

	test('reports the correct line number for a match past the first line', () => {
		const violations = findInlineSpecifiedViolations([
			{ path: 'src/baz.ts', text: "const a = 1;\nconst b = 2;\nif (stage === 'specified') {}\n" },
		]);
		expect(violations).toEqual([{ path: 'src/baz.ts', line: 3 }]);
	});

	test('a custom allowlist can permit a different file', () => {
		const violations = findInlineSpecifiedViolations(
			[{ path: 'src/other/allowed.ts', text: "stage === 'specified'\n" }],
			['src/other/allowed.ts'],
		);
		expect(violations).toEqual([]);
	});
});

// ---------------------------------------------------------------------------
// Real tree scan: the actual gate
// ---------------------------------------------------------------------------

describe('spine guard — real src/ tree', () => {
	test('src/ has zero inline stage===specified comparisons outside src/issues/plannable.ts', () => {
		const cwd = process.cwd();
		const glob = new Glob('src/**/*.{ts,tsx}');
		const allPaths = [...glob.scanSync({ cwd })];
		// src/vendor/ is excluded from the scan root; see file header comment.
		const scannable = allPaths.filter((p) => !p.startsWith('src/vendor/'));
		const files = scannable.map((p) => ({
			path: p,
			text: readFileSync(join(cwd, p), 'utf8'),
		}));

		const violations = findInlineSpecifiedViolations(files);
		expect(violations).toEqual([]);
	});
});
