#!/usr/bin/env bun
// scripts/generate-embedded-vendor.ts
//
// Codegen step: reads each file in `vendor/` and `templates/` that cam-cli
// embeds and writes their contents as raw string constants to
// `src/vendor/_generated.ts`. The generated module is the single source of
// truth for `src/vendor/embedded.ts` and `src/templates/embedded.ts` at
// runtime — both in dev (`bun src/...`) and in the compiled binary
// (`bun build --compile`). `bun build --compile` does NOT include arbitrary
// files in the binary; only TS modules transitively imported. Embedding as
// string constants is what makes runtime materialization work after
// install.
//
// Why a codegen rather than `with { type: "text" }` import attributes?
//
//   1. The vendored smoke files have `.ts` extensions. When TypeScript
//      resolves a `with { type: "text" }` import of a `.ts` file, it still
//      typechecks the target — and `vendor/check-agent-frontmatter.ts` /
//      `vendor/claude-auto-retry-patterns.ts` are vendored byte-for-byte
//      from the reporter monorepo, where they typecheck under a looser
//      tsconfig (no `noUncheckedIndexedAccess`). Adding `@ts-nocheck` to
//      the vendored copies would make the byte-diff smoke
//      (`test/vendor.test.ts`) fail.
//
//   2. The codegen output is plain TS literals — no exotic loaders, no
//      compiler-specific behavior. It works identically with `bun src/...`
//      and `bun build --compile`.
//
//   3. The generated file is checked in (NOT gitignored) so a fresh clone
//      can run tests + build without first running this script. The
//      `prebuild` hook in `package.json` re-runs it before any release
//      build, and `test/embedded.test.ts` asserts the generated contents
//      match the vendor files byte-for-byte (catches a stale codegen).
//
// Usage:
//   bun scripts/generate-embedded-vendor.ts              # writes the file
//   bun scripts/generate-embedded-vendor.ts --check      # exits 1 if drift

import { readFileSync, writeFileSync, existsSync, readdirSync, statSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import process from 'node:process';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(HERE, '..');
const VENDOR_DIR = join(REPO_ROOT, 'vendor');
const TEMPLATES_DIR = join(REPO_ROOT, 'templates');
const OUT_PATH = join(REPO_ROOT, 'src', 'vendor', '_generated.ts');

// Stable basename → const-name mapping. Listed alphabetically so the
// generated file has a deterministic ordering across machines.
const FILES = [
	{ basename: 'check-agent-frontmatter.sh', constName: 'checkAgentFrontmatterShContents' },
	{ basename: 'check-agent-frontmatter.ts', constName: 'checkAgentFrontmatterTsContents' },
	{ basename: 'claude-auto-retry-patterns.ts', constName: 'claudeAutoRetryPatternsContents' },
	{ basename: 'cam-loop-stop-hook.sh', constName: 'camLoopStopHookContents' },
	{ basename: 'cam-loop.local.md.tmpl', constName: 'camLoopTmplContents' },
] as const;

/**
 * Escape a string into a double-quoted JS literal. We use double quotes +
 * `\n` escaping (rather than backticks/template literals) because vendored
 * shell scripts may contain backticks for command substitution which would
 * silently break a template literal, and `JSON.stringify` is the safest way
 * to round-trip arbitrary content.
 */
function jsLiteral(value: string): string {
	return JSON.stringify(value);
}

/**
 * Walk `dir` recursively and return every file as a relative-path string
 * (POSIX-style separators). Sorted for deterministic codegen output.
 */
function walkFiles(root: string): string[] {
	const out: string[] = [];
	const stack: string[] = [root];
	while (stack.length > 0) {
		const cur = stack.pop()!;
		for (const entry of readdirSync(cur)) {
			const abs = join(cur, entry);
			const s = statSync(abs);
			if (s.isDirectory()) {
				stack.push(abs);
			} else if (s.isFile()) {
				out.push(abs);
			}
		}
	}
	return out
		.map((abs) => relative(root, abs).split(/[/\\]/).join('/'))
		.sort();
}

function generate(): string {
	const lines: string[] = [
		'// src/vendor/_generated.ts',
		'//',
		'// AUTOGENERATED — do not edit by hand. Run',
		'// `bun scripts/generate-embedded-vendor.ts` after editing anything in',
		'// `vendor/` or `templates/`. The CI smoke (`test/embedded.test.ts`)',
		'// asserts this file matches the on-disk contents.',
		'//',
		'// Source: scripts/generate-embedded-vendor.ts',
		'',
		'/* eslint-disable */',
		'',
	];
	for (const { basename, constName } of FILES) {
		const path = join(VENDOR_DIR, basename);
		if (!existsSync(path)) {
			throw new Error(`vendor file missing: ${path}`);
		}
		const contents = readFileSync(path, 'utf8');
		lines.push(`/** Inlined from \`vendor/${basename}\` (${contents.length} chars). */`);
		lines.push(`export const ${constName}: string = ${jsLiteral(contents)};`);
		lines.push('');
	}

	// --- templates/ -----------------------------------------------------------
	if (!existsSync(TEMPLATES_DIR)) {
		throw new Error(`templates dir missing: ${TEMPLATES_DIR}`);
	}
	const templateFiles = walkFiles(TEMPLATES_DIR);
	lines.push(
		`/** Inlined from \`templates/\` (${templateFiles.length} files). Keys are POSIX-style relative paths. */`,
	);
	lines.push('export const templatesContents: Readonly<Record<string, string>> = Object.freeze({');
	for (const relPath of templateFiles) {
		const contents = readFileSync(join(TEMPLATES_DIR, relPath), 'utf8');
		lines.push(`\t${jsLiteral(relPath)}: ${jsLiteral(contents)},`);
	}
	lines.push('});');
	lines.push('');

	// Final trailing-newline policy: exactly one. Same shape every run.
	return lines.join('\n').replace(/\n+$/, '\n');
}

function main(): number {
	const check = process.argv.includes('--check');
	const generated = generate();
	if (check) {
		const existing = existsSync(OUT_PATH) ? readFileSync(OUT_PATH, 'utf8') : '';
		if (existing !== generated) {
			process.stderr.write(
				`drift: ${OUT_PATH} is stale. Run \`bun scripts/generate-embedded-vendor.ts\` and commit the result.\n`,
			);
			return 1;
		}
		process.stdout.write(`ok: ${OUT_PATH} is up to date\n`);
		return 0;
	}
	writeFileSync(OUT_PATH, generated, 'utf8');
	process.stdout.write(`wrote ${OUT_PATH} (${generated.length} chars)\n`);
	return 0;
}

if (import.meta.main) {
	process.exit(main());
}
