#!/usr/bin/env bun
// scripts/generate-embedded-vendor.ts
//
// Codegen step: reads each file in `vendor/` that ralph-cli embeds and
// writes their contents as raw string constants to
// `src/vendor/_generated.ts`. The generated module is the single source of
// truth for `src/vendor/embedded.ts` at runtime — both in dev (`bun
// src/...`) and in the compiled binary (`bun build --compile`).
//
// Why a codegen rather than `with { type: "text" }` import attributes?
//
//   1. The vendored smoke files have `.ts` extensions. When TypeScript
//      resolves a `with { type: "text" }` import of a `.ts` file, it still
//      typechecks the target — and `vendor/check-agent-frontmatter.ts` /
//      `vendor/claude-auto-retry-patterns.ts` are vendored byte-for-byte
//      from the reporter monorepo, where they typecheck under a looser
//      tsconfig (no `noUncheckedIndexedAccess`). Adding `@ts-nocheck` to
//      the vendored copies would make the byte-diff smoke
//      (`test/vendor.test.ts`) fail.
//
//   2. The codegen output is plain TS literals — no exotic loaders, no
//      compiler-specific behavior. It works identically with `bun src/...`
//      and `bun build --compile`.
//
//   3. The generated file is checked in (NOT gitignored) so a fresh clone
//      can run tests + build without first running this script. The
//      `prebuild` hook in `package.json` re-runs it before any release
//      build, and `test/embedded.test.ts` asserts the generated contents
//      match the vendor files byte-for-byte (catches a stale codegen).
//
// Usage:
//   bun scripts/generate-embedded-vendor.ts              # writes the file
//   bun scripts/generate-embedded-vendor.ts --check      # exits 1 if drift

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import process from 'node:process';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(HERE, '..');
const VENDOR_DIR = join(REPO_ROOT, 'vendor');
const OUT_PATH = join(REPO_ROOT, 'src', 'vendor', '_generated.ts');

// Stable basename → const-name mapping. Listed alphabetically so the
// generated file has a deterministic ordering across machines.
const FILES = [
	{ basename: 'check-agent-frontmatter.sh', constName: 'checkAgentFrontmatterShContents' },
	{ basename: 'check-agent-frontmatter.ts', constName: 'checkAgentFrontmatterTsContents' },
	{ basename: 'claude-auto-retry-patterns.ts', constName: 'claudeAutoRetryPatternsContents' },
	{ basename: 'ralph-loop-stop-hook.sh', constName: 'ralphLoopStopHookContents' },
	{ basename: 'ralph-loop.local.md.tmpl', constName: 'ralphLoopTmplContents' },
] as const;

/**
 * Escape a string into a double-quoted JS literal. We use double quotes +
 * `\n` escaping (rather than backticks/template literals) because vendored
 * shell scripts may contain backticks for command substitution which would
 * silently break a template literal, and `JSON.stringify` is the safest way
 * to round-trip arbitrary content.
 */
function jsLiteral(value: string): string {
	return JSON.stringify(value);
}

function generate(): string {
	const lines: string[] = [
		'// src/vendor/_generated.ts',
		'//',
		'// AUTOGENERATED — do not edit by hand. Run',
		'// `bun scripts/generate-embedded-vendor.ts` after editing anything in',
		'// `vendor/`. The CI smoke (`test/embedded.test.ts`) asserts this file',
		'// matches the on-disk vendor contents.',
		'//',
		'// Source: scripts/generate-embedded-vendor.ts',
		'',
		'/* eslint-disable */',
		'',
	];
	for (const { basename, constName } of FILES) {
		const path = join(VENDOR_DIR, basename);
		if (!existsSync(path)) {
			throw new Error(`vendor file missing: ${path}`);
		}
		const contents = readFileSync(path, 'utf8');
		lines.push(`/** Inlined from \`vendor/${basename}\` (${contents.length} chars). */`);
		lines.push(`export const ${constName}: string = ${jsLiteral(contents)};`);
		lines.push('');
	}
	// Final trailing-newline policy: exactly one. Same shape every run.
	return lines.join('\n').replace(/\n+$/, '\n');
}

function main(): number {
	const check = process.argv.includes('--check');
	const generated = generate();
	if (check) {
		const existing = existsSync(OUT_PATH) ? readFileSync(OUT_PATH, 'utf8') : '';
		if (existing !== generated) {
			process.stderr.write(
				`drift: ${OUT_PATH} is stale. Run \`bun scripts/generate-embedded-vendor.ts\` and commit the result.\n`,
			);
			return 1;
		}
		process.stdout.write(`ok: ${OUT_PATH} is up to date\n`);
		return 0;
	}
	writeFileSync(OUT_PATH, generated, 'utf8');
	process.stdout.write(`wrote ${OUT_PATH} (${generated.length} chars)\n`);
	return 0;
}

if (import.meta.main) {
	process.exit(main());
}
