// scripts/validate-agents-md.ts
//
// Doc-as-code checker (US-001, CAM-61 PRD).
//
// Treats three classes of command/script/path claims embedded in backtick
// spans of the repo's own agent docs as machine-checkable assertions, so a
// stale reference (the 2026-06-05 stale-comment lesson, see
// scripts/cam/patterns.archive.md) fails a gate instead of silently rotting.
//
// Scanned surface (and ONLY this surface):
//   - CLAUDE.md (repo root)
//   - scripts/cam/CLAUDE.md
//   - .claude/agents/*.md
//
// templates/** is never scanned: its scripts/cam/... references resolve
// against a materialized target project, not this repo (US-001 notes).
//
// Claim classes, in priority order per backtick span:
//   1. `cam <cmd>` -- first word after "cam" validated against the COMMANDS
//      array exported by index.ts.
//   2. `bun run <script>` -- the script token validated against
//      package.json's `scripts` keys.
//   3. Backtick path-claims -- validated against the git-TRACKED tree (`git
//      ls-files`), NOT the live working tree (see isPathClaimCandidate /
//      resolvesInTrackedTree below). A claim fails ONLY when it is untracked
//      AND not git-ignored AND not in KNOWN_MISSING; a git-ignored claim is
//      treated as a declared ephemeral and auto-exempted, so runtime
//      artifacts (worker-report.json, cam-worker-events.jsonl, etc.) neither
//      mask nor trip the gate regardless of whether they happen to be
//      physically present on disk when the gate runs (US-R2-001, CAM-61).
//
// KNOWN_MISSING is an inline allowlist of glob-capable { pattern, reason }
// entries exempting path-claims that are genuinely untracked AND unignored
// (bare-filename shorthand, illustrative placeholders, forward-looking
// guardrails) -- NOT gitignored runtime artifacts, which the auto-exempt
// above already covers. Any entry that matches nothing during a run is
// reported as a non-fatal warning (dead-allowlist-entry guard) -- it does
// not fail the run.
//
// Usage: bun scripts/validate-agents-md.ts

import { Glob } from 'bun';
import { spawnSync } from 'node:child_process';
import { join } from 'node:path';
import process from 'node:process';
import { COMMANDS } from '../index.ts';

// ---------------------------------------------------------------------------
// Scan surface
// ---------------------------------------------------------------------------

/** Fixed, non-glob doc files scanned every run (repo-root relative). */
export const SCAN_FILES = ['CLAUDE.md', 'scripts/cam/CLAUDE.md'] as const;

/** Glob for the agent persona files. Single `*` -- never recurses into subdirs. */
export const AGENTS_GLOB = '.claude/agents/*.md';

/**
 * Resolve the full list of repo-relative doc paths to scan this run.
 * templates/** is never part of this list by construction: it is not one of
 * SCAN_FILES and does not match AGENTS_GLOB.
 */
export function resolveScanTargets(cwd: string): string[] {
	const targets: string[] = [...SCAN_FILES];
	const glob = new Glob(AGENTS_GLOB);
	for (const file of glob.scanSync({ cwd, dot: true })) {
		targets.push(file);
	}
	return targets.sort();
}

// ---------------------------------------------------------------------------
// KNOWN_MISSING allowlist
// ---------------------------------------------------------------------------

export interface KnownMissingEntry {
	/** Glob-capable pattern (matched via Bun.Glob#match against the stripped path-claim string). */
	pattern: string;
	/** Non-empty human-readable justification for why this claim never resolves on disk. */
	reason: string;
}

export const KNOWN_MISSING: KnownMissingEntry[] = [
	{
		pattern: 'scripts/cam/prd.json',
		reason: 'generated by /cam-plan; absent until a PRD has been planned (not gitignored: committed once planned)',
	},
	{
		pattern: 'scripts/cam/handoff.json',
		reason:
			'per-branch harness state git-rm\'d by ship-finalize (src/commands/ship-finalize.ts harnessPaths); cited by full path in .claude/agents/*.md, so it is absent on the shipped/main tree (US-R2-002, CAM-61)',
	},
	{
		pattern: 'scripts/cam/journal.archive.md',
		reason: 'created lazily by `cam journal archive`; absent until the journal is first archived',
	},
	{
		pattern: '/cam-*',
		reason: 'slash-command reference (.claude/commands/cam-*.md), not a filesystem path',
	},
	{
		pattern: '/exit',
		reason: 'built-in Claude Code slash command, not a filesystem path',
	},
	{
		pattern: 'foo.json',
		reason: 'illustrative placeholder filename in an oracle-kind example (subagent-auditor.md), not a real path',
	},
	{
		pattern: 'prd.json',
		reason: 'bare-filename shorthand for scripts/cam/prd.json used throughout agent docs for prose readability',
	},
	{
		pattern: 'handoff.json',
		reason: 'bare-filename shorthand for scripts/cam/handoff.json used throughout agent docs for prose readability',
	},
	{
		pattern: 'worker-report.json',
		reason: 'bare-filename shorthand for scripts/cam/worker-report.json used throughout agent docs for prose readability',
	},
	{
		pattern: 'review-report.json',
		reason: 'bare-filename shorthand for scripts/cam/review-report.json used throughout agent docs for prose readability',
	},
	{
		pattern: 'handoff.schema.json',
		reason: 'bare-filename shorthand for scripts/cam/handoff.schema.json used throughout agent docs for prose readability',
	},
	{
		pattern: 'journal.md',
		reason: 'bare-filename shorthand for scripts/cam/journal.md used throughout agent docs for prose readability',
	},
	{
		pattern: 'patterns.md',
		reason: 'bare-filename shorthand for scripts/cam/patterns.md used throughout agent docs for prose readability',
	},
	{
		pattern: 'lessons.md',
		reason: 'retired filename mentioned for historical context in scripts/cam/CLAUDE.md; replaced by lessons.archive.md',
	},
	{
		pattern: 'memory/',
		reason: 'created lazily per the Knowledge-Layer Routing table; absent until the first cross-cutting decision is filed',
	},
	{
		pattern: 'run.ts',
		reason: 'bare-filename shorthand for src/commands/run.ts used in subagent-orchestrator.md prose',
	},
	{
		pattern: 'setup.ts',
		reason: 'bare-filename shorthand for src/commands/setup.ts used in subagent-orchestrator.md prose',
	},
	{
		pattern: 'orch-agent-allowlist.sh',
		reason: 'bare-filename shorthand for .claude/hooks/orch-agent-allowlist.sh used in subagent-orchestrator.md prose',
	},
	{
		pattern: '.cam-orch-handoff.json',
		reason: 'bare-filename shorthand for .claude/.cam-orch-handoff.json, a runtime marker absent in a fresh checkout',
	},
	{
		pattern: '.cam-orch-handoff.consumed.json',
		reason: 'bare-filename shorthand for .claude/.cam-orch-handoff.consumed.json, a runtime marker absent in a fresh checkout',
	},
	{
		pattern: 'scripts/cam/issues/CAM-XXXX.json',
		reason: 'templated placeholder issue id in subagent-planner.md prose, not a real path',
	},
	{
		pattern: 'postgres.js',
		reason: 'npm package name mentioned in the Bun boilerplate CLAUDE.md (do not use pg or postgres.js), not a repo path',
	},
	{
		pattern: 'frontend.tsx',
		reason: 'illustrative example filename in the Bun boilerplate CLAUDE.md frontend snippet, not a repo path',
	},
	{
		pattern: '.githooks/**',
		reason:
			'forward-looking guardrail path in the implementer must-not-touch list; this repo uses .git/hooks (core.hooksPath default), so .githooks/ never exists on disk, but the constraint stays in case that convention is adopted later',
	},
];

// ---------------------------------------------------------------------------
// Backtick span extraction
// ---------------------------------------------------------------------------

const FENCED_CODE_BLOCK_RE = /```[\s\S]*?```/g;

/**
 * Strip fenced code blocks (```...```) so they can never be mis-tokenized by
 * the single-backtick span regex below (a triple-backtick fence is 3
 * consecutive backtick characters, which otherwise pairs up with unrelated
 * single backticks elsewhere in the doc and produces bogus multi-line spans).
 */
export function stripFencedCodeBlocks(text: string): string {
	return text.replace(FENCED_CODE_BLOCK_RE, '');
}

/** Extract the inner text of every `backtick span` in a doc, in order of appearance. */
export function extractBacktickSpans(text: string): string[] {
	const spans: string[] = [];
	const re = /`([^`]+)`/g;
	const withoutFences = stripFencedCodeBlocks(text);
	let match: RegExpExecArray | null;
	while ((match = re.exec(withoutFences)) !== null) {
		const span = match[1];
		if (span !== undefined) spans.push(span);
	}
	return spans;
}

// ---------------------------------------------------------------------------
// cam-cmd claims
// ---------------------------------------------------------------------------

const CAM_CMD_RE = /^cam\s+([A-Za-z][\w-]*)/;

/** If `span` is a `cam <cmd>` claim, return the claimed command token; else undefined. */
export function extractCamCommand(span: string): string | undefined {
	const match = CAM_CMD_RE.exec(span);
	return match?.[1];
}

// ---------------------------------------------------------------------------
// bun-run claims
// ---------------------------------------------------------------------------

const BUN_RUN_RE = /^bun run\s+([\w:-]+)/;

/** If `span` is a `bun run <script>` claim, return the claimed script key; else undefined. */
export function extractBunRunScript(span: string): string | undefined {
	const match = BUN_RUN_RE.exec(span);
	return match?.[1];
}

// ---------------------------------------------------------------------------
// Path-claim heuristic (AC4)
// ---------------------------------------------------------------------------

const PATH_EXT_RE = /\.(ts|tsx|js|json|sh|md)$/;

/**
 * Characters that disqualify a span from being a filesystem path-claim:
 * regex/shell metacharacters (grouping, alternation, redirection, template
 * placeholders, home-dir expansion) plus the explicit '$' from AC4. '*' is
 * deliberately NOT included -- glob-ish spans must still qualify.
 */
const DISALLOWED_METACHAR_RE = /[$^()|\\!?<>{}[\];&'",~]/;

const URL_SCHEME_RE = /^https?:\/\//;

/** True when `span` qualifies as a path-claim candidate per the AC4 heuristic. */
export function isPathClaimCandidate(span: string): boolean {
	if (span.includes(' ')) return false;
	if (DISALLOWED_METACHAR_RE.test(span)) return false;
	if (URL_SCHEME_RE.test(span)) return false;
	return span.includes('/') || PATH_EXT_RE.test(span);
}

const LINE_REF_RE = /:(\d+)(?:-\d+)?$/;

/** Strip a trailing `:NNN` or `:NNN-NNN` line-ref, returning the bare path. */
export function stripLineRef(span: string): string {
	return span.replace(LINE_REF_RE, '');
}

/**
 * Resolve a stripped path-claim against the git-TRACKED tree (`trackedFiles`,
 * the output of `git ls-files`), NOT the live working tree. A literal file
 * claim matches an exact entry; a directory claim (e.g. `.claude/agents`,
 * `claude-code-harness/`) matches when any tracked file sits under it; a
 * glob-ish claim (e.g. `.claude/agents/*.md`) matches via Bun.Glob against
 * every tracked file. This deterministically ignores whatever happens to
 * physically exist on disk at gate-run-time (US-R2-001, CAM-61).
 */
export function resolvesInTrackedTree(path: string, trackedFiles: readonly string[]): boolean {
	const normalized = path.endsWith('/') ? path.slice(0, -1) : path;
	if (trackedFiles.includes(normalized)) return true;

	const dirPrefix = `${normalized}/`;
	if (trackedFiles.some((file) => file.startsWith(dirPrefix))) return true;

	const glob = new Glob(normalized);
	return trackedFiles.some((file) => glob.match(file));
}

/** Injectable accessor for the git-tracked file list (`git ls-files`). */
export type GetTrackedFilesFn = () => string[];

/** Build a GetTrackedFilesFn that spawns `git ls-files` in `cwd`. */
export function makeGetTrackedFiles(cwd: string): GetTrackedFilesFn {
	return () => {
		const result = spawnSync('git', ['ls-files'], { encoding: 'utf8', cwd });
		if (result.status !== 0) {
			throw new Error(
				`git ls-files failed in ${cwd} (status ${result.status}): not a git repository / git unavailable`,
			);
		}
		return (result.stdout ?? '').split('\n').filter((line) => line.length > 0);
	};
}

/** Injectable accessor for git-ignore status of a single path-claim string. */
export type IsIgnoredFn = (path: string) => boolean;

/**
 * Build an IsIgnoredFn that spawns `git check-ignore -q <path>` in `cwd`.
 * Exit code 0 means ignored; a git-ignored path-claim is treated as a
 * declared ephemeral and auto-exempted (US-R2-001, CAM-61).
 *
 * `git check-ignore` also exits 128 for a fatal error caused by the `path`
 * argument itself (e.g. a slash-command-shaped claim like `/cam-next` reads
 * as an absolute path git considers "outside repository"), distinct from a
 * genuinely non-repo `cwd` or a missing `git` binary. Only the latter is a
 * cwd/tooling failure worth aborting the run over, so only a stderr fatal
 * naming "not a git repository" throws; any other 128 falls through as
 * not-ignored so the caller's KNOWN_MISSING allowlist can still exempt it.
 */
export function makeIsIgnored(cwd: string): IsIgnoredFn {
	return (path: string) => {
		const result = spawnSync('git', ['check-ignore', '-q', path], { cwd, encoding: 'utf8' });
		if (result.error !== undefined) {
			throw new Error(`git check-ignore failed in ${cwd}: git unavailable (${result.error.message})`);
		}
		if (result.status === 0) return true;
		if (result.status === 1) return false;
		if ((result.stderr ?? '').includes('not a git repository')) {
			throw new Error(
				`git check-ignore failed in ${cwd} (status ${result.status}): not a git repository / git unavailable`,
			);
		}
		return false;
	};
}

/** Return the first KNOWN_MISSING entry whose pattern matches `path`, if any. */
export function findKnownMissingMatch(
	path: string,
	entries: readonly KnownMissingEntry[],
): KnownMissingEntry | undefined {
	return entries.find((entry) => new Glob(entry.pattern).match(path));
}

// ---------------------------------------------------------------------------
// Findings
// ---------------------------------------------------------------------------

export interface Finding {
	file: string;
	span: string;
	kind: 'cam-cmd' | 'bun-run' | 'path';
	reason: string;
}

export interface ValidationResult {
	findings: Finding[];
	/** KNOWN_MISSING entries that never matched anything during the run. */
	unusedKnownMissing: KnownMissingEntry[];
}

export interface ValidationOptions {
	commands: readonly string[];
	bunScripts: readonly string[];
	knownMissing: KnownMissingEntry[];
	/** Root directory used for git plumbing (`git ls-files` / `git check-ignore`). */
	cwd: string;
	/** Git-tracked file list (`git ls-files` output) -- the deterministic source of truth for path-claim resolution. */
	trackedFiles: readonly string[];
	/** Returns true when a path-claim matches a .gitignore rule (declared-ephemeral auto-exempt). */
	isIgnored: IsIgnoredFn;
}

/** Validate a `cam <cmd>` claim; returns a Finding if the command is unknown. */
function checkCamCmdSpan(file: string, span: string, camCmd: string, commands: readonly string[]): Finding | undefined {
	if (commands.includes(camCmd)) return undefined;
	return { file, span, kind: 'cam-cmd', reason: `unknown cam command "${camCmd}"` };
}

/** Validate a `bun run <script>` claim; returns a Finding if the script key is unknown. */
function checkBunRunSpan(
	file: string,
	span: string,
	bunScript: string,
	bunScripts: readonly string[],
): Finding | undefined {
	if (bunScripts.includes(bunScript)) return undefined;
	return { file, span, kind: 'bun-run', reason: `unknown package.json script "${bunScript}"` };
}

/**
 * Validate a backtick path-claim span. Returns a Finding on failure, or
 * marks `matchedEntry` (via the returned `usedEntry`) when the claim is
 * exempted by the KNOWN_MISSING allowlist. A claim fails ONLY when it is
 * untracked AND not git-ignored AND not in KNOWN_MISSING (US-R2-001, CAM-61).
 */
function checkPathSpan(
	file: string,
	span: string,
	options: ValidationOptions,
): { finding?: Finding; usedEntry?: KnownMissingEntry } {
	if (!isPathClaimCandidate(span)) return {};

	const strippedPath = stripLineRef(span);
	if (resolvesInTrackedTree(strippedPath, options.trackedFiles)) return {};
	if (options.isIgnored(strippedPath)) return {};

	const usedEntry = findKnownMissingMatch(strippedPath, options.knownMissing);
	if (usedEntry !== undefined) return { usedEntry };

	return {
		finding: {
			file,
			span,
			kind: 'path',
			reason: `path claim "${strippedPath}" is untracked, not git-ignored, and not allowlisted`,
		},
	};
}

/** Classify and validate a single backtick span against all three claim classes. */
function checkSpan(
	file: string,
	span: string,
	options: ValidationOptions,
): { finding?: Finding; usedEntry?: KnownMissingEntry } {
	const camCmd = extractCamCommand(span);
	if (camCmd !== undefined) return { finding: checkCamCmdSpan(file, span, camCmd, options.commands) };

	const bunScript = extractBunRunScript(span);
	if (bunScript !== undefined) return { finding: checkBunRunSpan(file, span, bunScript, options.bunScripts) };

	return checkPathSpan(file, span, options);
}

/**
 * Validate a set of in-memory docs (each { path, text }) against the three
 * claim classes. Pure given `options`: callers inject `trackedFiles` /
 * `isIgnored` directly in tests (no real git calls needed for most cases) so
 * results never depend on the live repo staying static.
 */
export function validateDocs(
	docs: { path: string; text: string }[],
	options: ValidationOptions,
): ValidationResult {
	const findings: Finding[] = [];
	const usedKnownMissing = new Set<KnownMissingEntry>();

	for (const doc of docs) {
		for (const span of extractBacktickSpans(doc.text)) {
			const { finding, usedEntry } = checkSpan(doc.path, span, options);
			if (finding !== undefined) findings.push(finding);
			if (usedEntry !== undefined) usedKnownMissing.add(usedEntry);
		}
	}

	const unusedKnownMissing = options.knownMissing.filter((entry) => !usedKnownMissing.has(entry));
	return { findings, unusedKnownMissing };
}

// ---------------------------------------------------------------------------
// CLI entrypoint
// ---------------------------------------------------------------------------

async function main(): Promise<number> {
	const cwd = process.cwd();
	const targets = resolveScanTargets(cwd);
	const docs = await Promise.all(
		targets.map(async (path) => ({ path, text: await Bun.file(join(cwd, path)).text() })),
	);
	const pkgJson = JSON.parse(await Bun.file(join(cwd, 'package.json')).text()) as {
		scripts?: Record<string, string>;
	};

	const result = validateDocs(docs, {
		commands: COMMANDS,
		bunScripts: Object.keys(pkgJson.scripts ?? {}),
		knownMissing: KNOWN_MISSING,
		cwd,
		trackedFiles: makeGetTrackedFiles(cwd)(),
		isIgnored: makeIsIgnored(cwd),
	});

	for (const finding of result.findings) {
		process.stderr.write(`validate-agents-md: ${finding.file}: ${finding.reason} (span: \`${finding.span}\`)\n`);
	}

	for (const entry of result.unusedKnownMissing) {
		process.stderr.write(
			`validate-agents-md: warning: KNOWN_MISSING entry "${entry.pattern}" matched nothing this run\n`,
		);
	}

	if (result.findings.length > 0) return 1;
	process.stdout.write('validate-agents-md: ok\n');
	return 0;
}

if (import.meta.main) {
	main().then((code) => process.exit(code));
}
